### ISSUE TITLE
create a (this is a really bad name, but) `has_units` or some other convenience function?

### ISSUE THREAD

**Issue by jread-usgs** [appling/unitted#4]
Looking for a boolean response for the following thing:
```R
has_units(.Object, 'degC')
```
likewise, this would be nice too:
```R
has_units(c(.Object,.Object2), c('degC','mg ^-L'))
```

**Comment by jread-usgs** [comment]
maybe `validate_units(.Object, unit)`?

**Comment by aappling-usgs** [comment]
what i have already is
```verify_units(u(1,"x"), "x", list(T,F))``` if you want T/F output, or 
```verify_units(u(1,"x"), "x")``` if you want the value to be returned, unchanged, for use in chaining.
how does that sound to you?

**Comment by jread-usgs** [comment]
geeeez, thanks. Yeah, that is perfect. Was just writing something like that. Missed it in the doc.

**Comment by appling** [comment]
glad it's what you wanted. i'll add an issue for myself to make a better
overview doc so it's easier to find this stuff.

**Comment by jread-usgs** [comment]
Possibly turn your vignette into an html vignette? I found the ppt style to be kind of tricky to take in. Laura has a good one for EGRETci if you want to take a look
