### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by aappling-usgs** [appling/unitted#8]
```
Error in makePrototypeFromClassDef(properties, ClassDef, immediate, where) : 
  in constructing the prototype for class "unitted_ordered": prototype has class "S4", but the data part specifies class "integer"
Error : unable to load R code in package 'unitted'
ERROR: lazy loading failed for package 'unitted'
```
https://ci.appveyor.com/project/jread-usgs/mda-streams/build/0.1.101#L205

**Comment by jread-usgs** [comment]
note unstable R version https://ci.appveyor.com/project/jread-usgs/mda-streams/build/0.1.102#L104

**Comment by jread-usgs** [comment]
@aappling-usgs I am going to point our R to `R-stable` on appveyor instead of `R-devel`, ok? But you might want to look into this either way.

**Comment by aappling-usgs** [comment]
thanks. will do.

**Comment by appling** [comment]
can now replicate problem in appveyor build on this package:
https://ci.appveyor.com/project/appling/unitted/build/1.0.3#L231

**Comment by aappling-usgs** [comment]
The problem is with making an S4 object from the 'ordered' class - can reproduce the error without anything unitted in 1 line:
```r
> setClass('new_ordered', contains=c('ordered'))
Error in makePrototypeFromClassDef(properties, ClassDef, immediate, where) : 
  in constructing the prototype for class “new_ordered”: prototype has class “S4”, but the data part specifies class “integer”
> traceback()
4: stop(gettextf("in constructing the prototype for class %s: prototype has class %s, but the data part specifies class %s", 
       dQuote(className), dQuote(.class1(prototype)), dQuote(dataPartClass)), 
       domain = NA)
3: makePrototypeFromClassDef(properties, ClassDef, immediate, where)
2: completeClassDefinition(Class, classDef, where, doExtends = FALSE)
1: setClass("new_ordered", contains = c("ordered"))
```

**Comment by appling** [comment]
i'm stumped on making a unitted_ordered object that works in R-devel, but it turns out that `unitted_factor` can handle ordered factors with a little help on the deunitting side. going that route in commit 64c85f446d6946beb5a6e7fc6deb0473d65e5b17
